### ISSUE TITLE
Query parameter to hide information by default

### ISSUE THREAD

**Issue by CelebBattles** [jeffjose/redditpx#18]
Instead of loading a page and clicking on the hide button every time, it would be nice if there was a way to set it to "show" by using a query parameter.

**Comment by jeffjose** [comment]
query param will be tricky since all the query params are currently parsed as part of reddit api url. However, I can look to persist the show state onto localStorage. That way, if you have it hidden, it will remember next time you load.

**Comment by jeffjose** [comment]
Also, I noticed that you embed redditpx in your website. How are you embedding it? I noticed that the fullscreen button doesnt work. If you're using `iframe`, make sure you're setting `allowfullscreen` so that the button would work. ([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allowfullscreen))

**Comment by CelebBattles** [comment]
Just using the object tag like so.

```
<div>
      <object type="text/html" data="https://redditpx.com"></object>
</div>
```

Thanks, I will look into iframes.
