### ISSUE TITLE
User link

### ISSUE THREAD

**Issue by maitikeisi** [jeffjose/redditpx#6]
Hi,

I was wondering would it be possible to add username (w/clickable link similar to the subreddit that's already there) to the post title overlay? (see attached image, if not clear)

Thanks for the awesome redditp alternative!

![redditpx](https://user-images.githubusercontent.com/1008507/103217405-2e08a900-4921-11eb-935a-51c7dba4dec2.png)

**Comment by jeffjose** [comment]
Done. I deployed this on [stage.redditpx.com](stage.redditpx.com); Please play with it and let me know if things look stable. If I dont hear back, I'll promote the changes to redditpx.com proper in a few days.

![image](https://user-images.githubusercontent.com/173044/103249071-5644d780-4922-11eb-9369-21cde2f5dcdb.png)

**Comment by maitikeisi** [comment]
Thanks played around a bit and didn't notice anything strange so far.

Not directly related to this change (since it seems to happen on redditpx.com too), but I noticed that the preview hover images don't always load when viewing user's posts. 
i.e. https://redditpx.com/u/GeorgieWashington
Not sure whether it's just an issue at reddit's end. Similar behaviour can be seen happening on other users too.

![2020-12-29 05_23_41-](https://user-images.githubusercontent.com/1008507/103256590-7d3cf100-4996-11eb-8896-f832edb7585c.png)

**Comment by jeffjose** [comment]
Thanks for the repro. 

Just pushed a [fix](https://github.com/jeffjose/redditpx/commit/f7be27363dfec0af309f4e7c87d2ecea12b6643c) that (hopefully) should fix the issue but if you happen to find others please send them my way. In this particular case, reddit's API is NOT returning a field for some items and hence the missing image. The fix was essentially to fallback onto the main image. 

Changes are now live on stage.redditpx.com and redditpx.com.
